name: game_list_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  app_bar_with_search_switch: ^1.8.6
  curved_navigation_bar: ^1.0.6
  d_info: ^0.2.2
  extended_image: ^9.1.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.12
  http: ^1.3.0
  logger: ^2.5.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  toast: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true